### ISSUE TITLE
CMS design needs design documentation for OSS contribution

### ISSUE THREAD

**Issue by t1merickson** [decaporg/decap-cms#982]
Problem: 

Design of Netlify CMS is sporadic or maintained by just a few specific individuals. Design work suggested beyond those specific individuals does not have the benefit of understanding the underlying design system, style, and goals. 

Goal: 

Create a design system, component library, open source Sketch files, goal documents, mockups, and other tools to encourage designers in the OSS community to be able to contribute to design-specific work on Netlify CMS 

This is a start of a container for conversation around this large task, which will support individual design improvements to the CMS
  

Possible Todos:
1. Build a storybook library for design components
2. Draft wireframes for future major design work

Actual TODOs:

- [x] Setup an open/free Abstract (version control for Sketch files)
- [ ] Write a style guide document
- [ ] Create issues for good first design contribution
- [ ] Create better readme to talk about how to contribute design
- [ ] Create a specific document detailing how to contribute design

**Comment by owenhoskins** [comment]
Timely issue @neutyp. I came across this while searching issues in hopes of finding sketch assets to support the minor design needs of #1032. Are there some assets that could be made available at this point?

**Comment by neutyp** [comment]
@owenhoskins Yes! Good news for you. We're in the very early stages of a project with Abstract (think of it as GitHub for designers, it's literally version control for Sketch files) 

Here is a secret link to signup as a Contributor on our Abstract; https://app.goabstract.com/invitations/e54c6ba50ab4d0062755d9a503dfc3de3a1010dfaa39b49eb59ce863b67d7c91

PLEASE NOTE: 
1. Your contributor access allows you to create branches and merge. Please only create branches, do not merge to Master. You can then ping me in an GH Issue or PR if you'd like the work merged to Master and I will do it :) 
2. The work you're looking for is in the `Netlify CMS Core` repo on Abstract, simply create a branch of Master and you're off and away. Simply commit any changes to your branch through the Abstract Mac app. 
3. We're going to start creating contribution documentation and I'd love to ask for you feedback on how this process works and perhaps a bit of help writing the actual documentation :) 

Please let me know if you have any questions! I'm here to help

**Comment by neutyp** [comment]
@ziburski Can you do me a huge favor and follow the same process outlined above to signup as an Abstract contributor? Specifically if there's any `netlifycms.org` work newer than what's in the relevant project on Abstract? 

Also if you ever have desire or time to work on any further Netlify CMS improvements in the future, we'd love to track the Sketch work there!  Thanks again for being such a huge support on the design side of this project, your work has continually propelled us forward.

**Comment by tech4him1** [comment]
@neutyp Do you have a view/comment only link as well? If we wanted to, we could add that link to our public documentation, and have contributors ask for permission if they want to get write access.

**Comment by neutyp** [comment]
@tech4him1 Yes! This is the link anyone can use to be a Viewer/Guest which allows access even if you don't have a Mac or Sketch (can be used entirely on the web) 

https://app.goabstract.com/invitations/2c5318430729aaf2f02921bae52f524512e8a39e8f2636e5162b3fabce712ee2

**Comment by neutyp** [comment]
@tech4him1 Please note I copy pasted the wrong link; the above comment has now been updated with the right one

**Comment by tech4him1** [comment]
Working. Both links say that I'm added as a member -- I can't see if they give me different permissions, though, since I'm not on a Mac.

**Comment by neutyp** [comment]
@tech4him1 The links confused even me. I just gave feedback to Abstract privately about that, FYI. At any rate, on my backend I can confirm you signed up as a Viewer, and Lennart just signed up as a Contributor, so the links are working perfectly!

**Comment by ziburski** [comment]
> Specifically if there's any netlifycms.org work newer than what's in the relevant project on Abstract?

The one on Abstract is the latest Sketch file. The last iterations were done straight in markup and weren’t documented in Sketch. I agree it would be nice to have though.

I won’t have time to contribute much in the near future, but Abstract should make it very easy to follow along with the design process and chime in when something comes up. Props for trying that new approach!

**Comment by ziburski** [comment]
@neutyp Oh, I lied. I do have a slightly updated version of the website Sketch file. Just created a new branch on Abstract for it. Did I do it right? It takes a while to get used to the workflow in a design context.

**Comment by neutyp** [comment]
@ziburski yep, perfect! thanks for taking a moment to double check this!

**Comment by erquhart** [comment]
🎉🎉🎉 to all of this

**Comment by martinjagodic** [comment]
Closing as stale and/or outdated.
